---
# ansible/roles/apps/tasks/main.yml
- name: Get deploy user info
  user:
    name: "{{ deploy_user }}"
  register: deploy_user_info

- name: Deploy Node.js Apps via Quadlets
  template:
    src: app.container.j2
    dest: "/home/{{ deploy_user }}/.config/containers/systemd/{{ item.name }}.container"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0644'
  loop: "{{ apps }}"
  notify: Reload systemd user

- name: Ensure apps are started and enabled
  systemd:
    name: "{{ item.name }}"
    scope: user
    state: started
    enabled: yes
  become: yes
  become_user: "{{ deploy_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ deploy_user_info.uid }}"
  loop: "{{ apps }}"
