---
- name: Configure Infrastructure
  hosts: all
  become: yes
  roles:
    - { role: common, tags: common }
    - { role: podman, tags: podman }
    - { role: traefik, tags: traefik }
    - { role: monitoring, tags: monitoring }
    - { role: databases, tags: databases }
    - { role: apps, tags: apps }
