---
traefik_version: latest
traefik_acme_email: "admin@{{ main_domain }}"
traefik_config_dir: "/home/{{ deploy_user }}/traefik"
traefik_image: docker.io/library/traefik:{{ traefik_version }}

traefik_dashboard_user: admin
traefik_dashboard_pass: "$apr1$UaUfSwGI$ZcVz3zhZ9tzdN4ot8RiGA."

traefik_ratelimit_average: 100
traefik_ratelimit_burst: 50
